version: '3'
services:
 flood:
    image: kiralex/docker-image
    tty: true
    ports:
    - 49184:49184
    - 3000:3000
    - 49999:49999
    volumes:
    - /etc/letsencrypt/archive/kiralex.me/privkey1.pem:/rtorrent/sslKey.pem
    - /etc/letsencrypt/archive/kiralex.me/cert1.pem:/rtorrent/sslCert.pem
    - /home/seedbox/downloads:/downloads
    - /home/seedbox/flood:/rtorrent/flood/
 plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Paris
      - PLEX_CLAIM=claim-KS1FdzRMxLDJEqqZZvxN
      - ADVERTISE_IP=http://5.135.155.49:32400/
    hostname: kiralex.me
    volumes:
      - /home/seedbox/plex/config:/config
      - /home/seedbox/plex/trancode:/transcode
      - /home/seedbox/downloads:/data
      - /etc/letsencrypt/archive/kiralex.me/certificate.p12:/sslKey.pem
