version: '3'
services:
 flood:
    image: kiralex/docker-image
    tty: true
    ports:
    - 49184:49184
    - 3000:3000
    - 49999:49999
    volumes:
    - /etc/letsencrypt/archive/kiralex.me/privkey1.pem:/rtorrent/sslKey.pem
    - /etc/letsencrypt/archive/kiralex.me/cert1.pem:/rtorrent/sslCert.pem
    - /home/seedbox/downloads:/downloads
    - /home/seedbox/flood:/rtorrent/flood/
