version: 2
jobs:
 toto:
   machine: true
   steps:
     - checkout
     - run: date
 build:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     # build the application image
     - run: docker build -t kiralex/docker-image .

     # deploy the image
     - run: docker push kiralex/docker-image

workflows:
   version: 2
   build-master:
     jobs:
       - toto
       - build
     filters:
       branches:
         only: master
       tags:
         ignore: /*/

