version: 2
jobs:
 toto:
   machine: true
   steps:
     - checkout
     - run: date
 builda:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     # build the application image
     - run: docker build -t kiralex/docker-image .

     # deploy the image
     - run: docker push kiralex/docker-image

workflows:
   version: 2
   build-master:
     jobs:
       - builda:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
