version: 2
jobs:
 toto:
   machine: true
   steps:
     - checkout
     - run: date
 build:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t kiralex/docker-image .
     - run: docker push kiralex/docker-image

workflows:
   version: 2
   build-master:
     jobs:
       - build:
          filters:
                 #tags:
             #only: /.*/
            branches:
              only: /^master*/
             #ignore: /.*/


